### ISSUE TITLE
[Skyblocks] Changing spawners

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#11]
Losing spawners if you change them

VIDEO: https://youtu.be/oudtlTWWs0U

**Comment by LucKYsHoTSzZz** [comment]
List:
https://fadecloudmc.com/forums/threads/legomyegos-skyblock-destiny-bug-report.46834/

**Comment by FadeCloudINC** [comment]
Skyblock is being reset soon. this plugin wont be on there.
