### ISSUE TITLE
[Skyblocks] Generators

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#12]
Self explanatory. The return of the generators to Skyblock. I hope there are plans for that. Adding something unique back to the Skyblock servers.

**Comment by Inkzzz** [comment]
Why was it removed? @FadeCloudINC

**Comment by FadeCloudINC** [comment]
Dupes, asked for some things to be changed so we can avoid it but I no longer think I have it @Inkzzz

**Comment by Inkzzz** [comment]
We can always remake it to utilise our libraries then reimplement it.

**Comment by FadeCloudINC** [comment]
We can work on it after all other issues are resolved.
