### ISSUE TITLE
[Global] [item]

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#15]
[item] does not support 1.12 sometimes.

THREAD: https://fadecloudmc.com/forums/threads/uncriticals-skyblock-destiny-bug-report.45292/

**Comment by Inkzzz** [comment]
Reflection isn't great supporting 1.7 - 1.12 but it can be looked into nonetheless.

**Comment by Inkzzz** [comment]
Fixed by 1.12.1 + ViaVersion change.
