### ISSUE TITLE
[Global] Nicknames

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#19]
Basically, when using the nick command for a simple name such being 'lucky'.

So when you have the nick 'lucky' for a few days, you decide to remove your nick for a day. Then after a while you change your name back to 'lucky', but you can't because it says someone else is using it. Which is not correct (most of the times)

What I'm saying is that there should be "a fix" or "an other plugin" made to support the nicknames.

**Comment by kalebmmm** [comment]
That's essentials. It is first come first serve but we might be able to implement this into our essentials fork @Inkzzz ?

**Comment by Inkzzz** [comment]
Yeah we can implement it into essentials. Convert from bug to new features on a new issue.

**Comment by Inkzzz** [comment]
Close to turn into a feature; 

https://github.com/FadeCloudNW/issue-tracker/issues/41
