### ISSUE TITLE
[Prison] Global Boosters

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#2]
Global boosters do not apply to player who join after they launched. This basically means you have to be online when it launches or you will not get the booster.

VIDEO: https://youtu.be/8ZPOE0xkUhI

**Comment by Inkzzz** [comment]
When was this reported? We fixed this not long ago.

**Comment by LucKYsHoTSzZz** [comment]
I think the last time this occurred was the 11th of July (unsure about this date)

**Comment by FadeCloudINC** [comment]
Its been resolved.
