### ISSUE TITLE
[Skyblock2 (Luminous)]

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#25]
https://fadecloudmc.com/forums/threads/ds5s-skyblock-luminous-bug-report.46928/

Try an account with normal perms. Try saying {hi}

Note: does not occur on any other servers.

**Comment by kalebmmm** [comment]
No plugins should be messing with this? Chat plugin certainly isn't... @FadeCloudINC @Inkzzz

**Comment by Inkzzz** [comment]
What's the outcome of saying {hi}?

**Comment by FadeCloudINC** [comment]
Issue went away.

**Comment by LucKYsHoTSzZz** [comment]
It didn't go away. The outcome is just an empty message.
