### ISSUE TITLE
[Hubs] 1.7 Compatibility

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#26]
Recorded : https://www.youtube.com/watch?v=Z3yAA2Nlh24

This only happens if you stay longer than 10 seconds in hub. All other servers are fine.

**Comment by Inkzzz** [comment]
Closing due to 1.7. Aleksey can re-open if we decide to offer further compatibility, but I feel it is a waste of time, which is something we don't have.
