### ISSUE TITLE
Cobble buckets issue. [DUPE] [URGENT]

### ISSUE THREAD

**Issue by FadeCloudINC** [FadeCloudNW/issue-tracker#28]
Sand buckets should generate sand from down to up. You need to place the bucket at the bottom so it begins to generate up, otherwise there is a dupe when cobweb.

How it should work: https://www.youtube.com/watch?v=8XxPPiobuE4 begins at 0:24

**Comment by FadeCloudINC** [comment]
Also this issue: https://fadecloudmc.com/forums/threads/goflex_s-factions-bug-report.50989/

**Comment by kalebmmm** [comment]
Still can do web glitch with cobweb no matter how you make stacks of sand. There's no good way to prevent that.
