### ISSUE TITLE
[Prison] Energy Bottle

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#29]
Basically I would like to make it so the 100 blocks broken only works when mining in the mines. 

People can afk in spawn and break the 'unbreakable' ground and they're also making cobble gens on their plots to afk at.

**Comment by Inkzzz** [comment]
Sent for testing.

**Comment by Inkzzz** [comment]
Is this tested @FadeCloudINC?

**Comment by Inkzzz** [comment]
Closing due to being in "testing" state for over 15 days. If this issue comes up again, it'll be flagged up before any resets/changes.
