### ISSUE TITLE
[Prison] Gems

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#3]
Gems do not give you any blocks when using them.

VIDEO: https://youtu.be/TTmfy4-gsj4

**Comment by Inkzzz** [comment]
Worked on a potential fix and sent for testing.

**Comment by Inkzzz** [comment]
Assigned @FadeCloudINC for testing/review.

**Comment by FadeCloudINC** [comment]
Will be resolved next season. We modified a lot of features but cannot apply it to the live server because it will just break.
