### ISSUE TITLE
[Global] Titles

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#31]
https://fadecloudmc.com/forums/threads/doctornimrods-global-bug-report.49610/

Only happens in 1.7 if you copy what he does in the video it will do the same.

**Comment by Inkzzz** [comment]
This is an issue. It's regarding the GUI title. 1.7 gui inventory titles are smaller sized than any corresponding version (1.8+), Are we going to bother supporting 1.7? Seems like a waste of time considering it's a very retro version.

@FadeCloudINC

**Comment by kalebmmm** [comment]
1.7 in 2017
