### ISSUE TITLE
Enchant issues

### ISSUE THREAD

**Issue by FadeCloudINC** [FadeCloudNW/issue-tracker#32]
- Magnet enchant doesn't work with spawners. It should only work if you also have the silktouch enchant aswell.
- You can destroy peoples bases with the blaze enchant (possible obsidiandestroyer and magen too) regardless if its claimed.
- Mark : Does this even work. I'm getting complaint the chances are way too low or that the enchantment doesn't even work.

**Comment by Inkzzz** [comment]
Shall we prevent mining Magnet from activating on spawners?

**Comment by FadeCloudINC** [comment]
If you cant make it go straight into your inventory, then do that.

**Comment by Inkzzz** [comment]
Everything done & tested (exclusion of mark enchantment - opened a fresh issue)
