### ISSUE TITLE
[Prison] {DUPE} Energy

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#34]
You can withdraw energy so let's say 5000 and you can buy 2 empty bottles. Stack them onto each other and just apply the energy onto the stacked ones and it will fill both containers with 5k energy.

I hope this is enough info.

**Comment by LucKYsHoTSzZz** [comment]
Guess this can be closed, this is fixed for the next reset?

**Comment by Inkzzz** [comment]
No-one has worked on it yet. Leave it open till assigned and completed.

**Comment by Inkzzz** [comment]
The bug has been resolved.
