### ISSUE TITLE
[Global] AuctionHouse

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#4]
Auction house is acting weird on most server, from not receiving money to losing all items (upon reboot).

> Try putting a piece of paper on ah and come back after the daily reboot.

**Comment by LucKYsHoTSzZz** [comment]
Added a possible methode on how to reproduce this

**Comment by Inkzzz** [comment]
We're planning on rewriting this plugin. The new version will be more user-friendly and contain a lot more features. 

Labelling as "rewrite".

**Comment by kalebmmm** [comment]
Annnnd time for the reset and it's done with the exception of a couple features that don't affect usability. 🎉 🎉 👌👌👌👌
