### ISSUE TITLE
[Custom Enchants] Magnet 

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#45]
https://fadecloudmc.com/forums/threads/end4unows-skyblock-destiny-skyblock-luminous-bug-report.52852/

https://fadecloudmc.com/forums/threads/heuxs-skyblock-luminous-bug-report.53173/

Seems to be messing with all Vanilla enchantments other than Efficiency

**Comment by Inkzzz** [comment]
Closing this report as the tickets have been opened in the correct repo;
- https://github.com/FadeCloudNW/Enchantments/issues/23
- https://github.com/FadeCloudNW/Enchantments/issues/26
