### ISSUE TITLE
[Custom Enchant] Haste VS Accelerate

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#47]
Accelerate has more priority than the Haste enchantment. Meaning if you would hold an item with Haste III and wearing boots with Accelerate 1 it would choose the Accelerate which would result in a Haste I buff instead of a Haste III

**Comment by Inkzzz** [comment]
This ticket has been moved to the correct repository; https://github.com/FadeCloudNW/Enchantments/issues/27
