### ISSUE TITLE
Titles Issue // Chatcontrol (either one, not sure).

### ISSUE THREAD

**Issue by FadeCloudINC** [FadeCloudNW/issue-tracker#48]
Titles dont disable in chat when using the latest minecraft version. Could either be the titles plugin or fadechatcontrol.

**Comment by kalebmmm** [comment]
What do you mean don't disable in chat?

**Comment by FadeCloudINC** [comment]
Display, my apologies.

**Comment by Inkzzz** [comment]
Fade Chat Control set to be rewritten. Closing ticket.
