### ISSUE TITLE
[Factions] Glitch into bases with a boat

### ISSUE THREAD

**Issue by smartis2** [FadeCloudNW/issue-tracker#49]
https://www.youtube.com/watch?v=dMvPHDU0hlA

**Comment by Inkzzz** [comment]
Strong feeling this could be essentials.

**Comment by Inkzzz** [comment]
Any ideas @kalebmmm @FadeCloudINC?

**Comment by kalebmmm** [comment]
Placing my bets on NCP and Essentials
