### ISSUE TITLE
[Global] Boosters

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#5]
## **Work:**
* Prison Sell Booster(s)
* Survival Money x2 Booster
* Skyblock Money x2 Booster

## **Don't Work:**
* Skyblock's EXP x6 Booster
* Survival EXP x2 Booster
* Faction EXP x2 Booster
* Faction Money x2 Booster

## **Not Tested**
* Survival MCMMO x2 Booster
* Skyblock MCMMO x2 Booster
* Faction MCMMO x2 Booster

**Comment by Inkzzz** [comment]
Located a possible bug regarding experience boosters.

**Comment by Inkzzz** [comment]
Assigned @FadeCloudINC for testing of experience boosters.
