### ISSUE TITLE
[Auction House] Banned items

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#52]
Can you add that spawner with that 0 to a sort of banned list? I don't know if that has a specific ID or so https://fadecloudmc.com/forums/threads/player-report-kanjuros.53871/#post-251035

**Comment by Inkzzz** [comment]
Note to resolver:
- Just add a check to see if the item stack has an amount of less or equal to 0. This should resolve this issue.

**Comment by FadeCloudINC** [comment]
@kalebmmm

**Comment by kalebmmm** [comment]
Pushed a fix
