### ISSUE TITLE
[Factions] Autosell / sellchests signs

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#53]
You know that bug where ceggs and tnt don't break the sign. It's the explosion that doesn't take place near the sign. It's back

**Comment by Inkzzz** [comment]
Hello Kaleb,

The code that you previously wrote and made a pull request with essentials, can you ensure the code is present in our own version? You can find the repository at the following link https://github.com/FadeCloudNW/Essentials-2.x

Thanks,
Luke.

**Comment by kalebmmm** [comment]
We don't have my change.

**Comment by kalebmmm** [comment]
Is there any way to merge changes from essx @Inkzzz

**Comment by Inkzzz** [comment]
I can do that @kalebmmm if you provide me with the data to merge.

**Comment by kalebmmm** [comment]
@Inkzzz https://github.com/drtshock/Essentials/pull/1402

**Comment by Inkzzz** [comment]
Thanks - I'll look into it and have it merged.
