### ISSUE TITLE
Headflip and Comp

### ISSUE THREAD

**Issue by kalebmmm** [FadeCloudNW/issue-tracker#55]
Looks like headflip wins aren't updating in Comp

https://fadecloudmc.com/forums/threads/xkarinas-skyblock-luminous-bug-report.54688/#post-253750

**Comment by Inkzzz** [comment]
Headflip wins and loses must be unique in order to count. This was a newly added feature so the user could have previously had contributions count against the same individual. As of now, you must beat unique people. This helps prevent people "boosting" their stats.
