### ISSUE TITLE
Prison Issues

### ISSUE THREAD

**Issue by FadeCloudINC** [FadeCloudNW/issue-tracker#62]
- you can get lucky chests at the plot world.
- Placeholders dont work: https://prnt.sc/h0cd9y use iphones method if he told you what he does.
- You can make sell signs at plotworld again.
- http://prntscr.com/h0cbal make it exit the GUI if you dont have enough orbs to upgrade your pickaxe and remove the upgraded enchant to level 0 message.
- /orbstop needs to be added.
- make it so you receive 1 enchant from every pickaxe level up (dont give 2 enchants).

**Comment by Inkzzz** [comment]
Does /orbstop prevent just orbs being received from mining?

**Comment by Inkzzz** [comment]
Did you revert versions? "You can make sell signs at plotworld again."

**Comment by FadeCloudINC** [comment]
No no, /orbstop = orbs top - should display the players with the top orbs, we had this for tokens but its not working because of the changes.

I used the version you gave me for the plotworld issue.

**Comment by Inkzzz** [comment]
Did you update the jar file after I uploaded one? If so yours may be outdated. I can send you the current version, however.

**Comment by Inkzzz** [comment]
Do you want the orbs top to be displayed in a gui?

**Comment by FadeCloudINC** [comment]
I used it on my localhost server

**Comment by FadeCloudINC** [comment]
yes display it in a gui

**Comment by FadeCloudINC** [comment]
Looks like everything works above but found new issues:
- Boosters should add onto your multiplier instead of stop it. so if you have a 3x and you use a 1.5x booster, you should get 3.5x.
- Add an alias command to the top orbs plugin, make it /toporbs
