### ISSUE TITLE
Prison Issues

### ISSUE THREAD

**Issue by FadeCloudINC** [FadeCloudNW/issue-tracker#63]
- [x] - Boosters should add onto your multiplier instead of stop it. so if you have a 3x and you use a 1.5x booster, you should get 3.5x.
- [x] - Top orbs command doesn't display the top 1-10 players. Displays 10+ ranked players.
- [x] - Add an alias command to the top orbs plugin, make it /toporbs
- [x] - You can spawn lucky chests at spawn, make it so you can only spawn it in the configured regions.
- [x] - Need the disenchanter ASAP.

**Comment by dubz1080** [comment]
Flight issue is not only on prison but all servers.

**Comment by Inkzzz** [comment]
Boosters should add onto your multiplier instead of stop it. so if you have a 3x and you use a 1.5x booster, you should get 3.5x.
- Is this for multiplier-signs or boosters?

**Comment by Inkzzz** [comment]
If you use a global orb booster, players who login after the boost was activated will not receive the booster.

Is this the same for all other booster types?

**Comment by Inkzzz** [comment]
Solutions provided for:
- Top orbs command doesn't display the top 1-10 players. Displays 10+ ranked players.
- Add an alias command to the top orbs plugin, make it /toporbs
- You can spawn lucky chests at spawn, make it so you can only spawn it in the configured regions.

**Comment by Inkzzz** [comment]
Waiting on @kalebmmm regarding the flight issue.

**Comment by FadeCloudINC** [comment]
Boosters should add onto your multiplier instead of stop it. so if you have a 3x and you use a 1.5x booster, you should get 3.5x.
- Multiplier signs

If you use a global orb booster, players who login after the boost was activated will not receive the booster.
- Not sure about other boosters, assuming not because boosters and multipliersigns are different plugins.

The flight issue has nothing to do with essentials, I'm using the flight plugin that uses platform. You coded it.

**Comment by Inkzzz** [comment]
Minusing content from "FadeBooster" as it is planned to be rewritten into our new system.

**Comment by Inkzzz** [comment]
Flight bug removed as it isn't a prison-specific issue.

**Comment by Inkzzz** [comment]
Closing this ticket as it has been separated to its preferenced repositories or the issue has been resolved [deployed].

**Comment by FadeCloudINC** [comment]
Reopened
- Flight bug is a prison-related issue. Need that's resolved asap.

**Comment by FadeCloudINC** [comment]
Nvm closed, didnt notice the current opened issues.
