### ISSUE TITLE
Iphony (Issues)

### ISSUE THREAD

**Issue by FadeCloudINC** [FadeCloudNW/issue-tracker#66]
Prison Issues
--------------------------

- [x] Tab error: https://pastebin.com/Mfmv8SA0

- [ ] Placeholders needed: 
Current prison rank (rankup[vault] is the plugin)
Rankup money required (its already there for featherboard but it keeps breaking, make it a placeholderapi and fix the breaking) 
Please use placeholder api.

- [x] Prison Particles:
DragonBurst - dragonbreath particle
Genesis - angryVillager
Angelic - witchMagic
Lightining - Lightning strike
Explosion - large explosion
lv 1 - 2 of those particles ^
Every 250 levels add 1 more of those particles

Factions Issues
--------------------------
- [x] Factions tab isnt in order.

Global Issues
----------------------------
- [x] https://prnt.sc/h5ko17 add a broadcast to when these are opened. (drops plugin)
```

&b&l(&f&l!&b&l) %name% has given everyone an epic key
&7Make sure to send them a tip for their mini drop party.

```

**Comment by dubz1080** [comment]
For placeholder sometimes the orb counter breaks and a /hub is needed to fix

**Comment by dubz1080** [comment]
Greed booster stays on account http://prntscr.com/h5vtco

**Comment by FadeCloudINC** [comment]
Particle Issues 
--------------------
- [ ] Lightning shoots out like 50 lightning strikes. Only one is needed.
- [ ] Explosion has a huge explosion particle that flashes your screen, need that a lot smaller.
- [ ] Change angelic particle to happyVillager

**Comment by Inkzzz** [comment]
How's this progress going @kalebmmm?

**Comment by kalebmmm** [comment]
@Inkzzz Updated what I have. Forgot about the placeholders.
