### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by FadeCloudINC** [FadeCloudNW/issue-tracker#68]
Global
---------------
- [x] Fadekits lore  changes:
If available: https://prnt.sc/hg5chk
```
&a&l%kitname%
&7Left click to use
&7Right click to preview

&a[Kit is ready for use]
```

If on cooldown
```
&e&l%kitname%
&7Left click to use
&7Right click to preview

&e[Cooldown: %time%]
```

If no permission
```
&c&l%kitname%
&7Purchase this kit @ &cstore.fadecloud.com
&7Right click to preview

&c[No access to this kit]
```

- [x] Fadekits gui should be 3 rows
- [x] Have kits start from the first gui slot
- [x] Kits with access = green pane item
kits with no access = red pane item
kits on cooldown = yellow pane item

Prison
-------------
- [x] https://prnt.sc/hfxv6b %rankup_rank% placeholder for prison is not displaying the players rank.

Factions
-------------
- [x] Factions tab isnt in order.

Skyblock
-------------
- [ ] Allow spawners to spawn in any condition. Meaning, if you have a pig spawner, let it spawn on bedrock or any kind of block. Also make sure that the time in minecraft isnt affecting spawners.
- [ ] Mobs dont stack sometimes, due to the island upgrades plugin.
- [x] Make the mob drops upgrade a chance base for 2x drops. lv 1 - 20% chance, lv 2 - 40% chance etc..

**Comment by kalebmmm** [comment]
Factions tab is ordered by faction then rank? http://prntscr.com/hg3msm

**Comment by FadeCloudINC** [comment]
Should be by rank @kalebmmm

**Comment by Inkzzz** [comment]
I resolved rank up placeholders the other day.

I am going to open the remaining issues within a new ticket.
