### ISSUE TITLE
[Title Plugin] Colo(u)ring titles

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#69]
./titlecolor , /colortitle works fine. It just does not remember the colo(u)ring upon relogging to the network. This seems to be random. Meaning there are times where it does remember it

Also this:
http://prntscr.com/homjc8
relogged went to the same server:
http://prntscr.com/homjj2

**Comment by Inkzzz** [comment]
Moved -> https://github.com/FadeCloudNW/Titles/issues/7
