### ISSUE TITLE
Prison Enchantments

### ISSUE THREAD

**Issue by FadeCloudINC** [FadeCloudNW/issue-tracker#7]
Couple of issues & changes with the prison enchants plugin:

- endstone should not go into your inventory, it should disappear after you mine it.

- https://gyazo.com/dc75e84520e44866178f4e49b52cd972 level information should always be at the bottom of enchantments.

- https://gyazo.com/dc75e84520e44866178f4e49b52cd972 
Change the pickaxe lores when you place an enchantment to:
Efficiency: default minecraft lore
Fortune: default minecraft lore
Unbreaking: default minecraft lore
Bunny: &aBunny #
Sonic: &bSonic #
Haste: &1Haste #
Repair: &eRepair #
Explosion: &4Explosion #
Knowledge: &2Knowledge #
Angelic: &5Angelic #
Money: &6Money #
Lightning: &bLightning #

- You do not receive a random enchantment for leveling up your pickaxe: 
"Everytime you level up, you receive one of the following :
+10 fortune (20% chance to get)
+25 efficiency (20% chance to get)
+25 unbreaking (20% chance to get)
+10 explosion (20% chance to get)
+10 angelic (20% chance to get)
+10 lightning (20% chance to get)
+1 sonic (5% chance to get)
+1 bunny (5% chance to get)
+1 knowledge (10% chance to get)
+1 Money (10% chance to get)
+1 repair (10% chance to get)"

- Level 2 pickaxe should have 1000 exp, not 500.
"Lv 1 -> 10 = increase by 500 blocks (while level 1 is 500 blocks, so level 10 is 5k blocks)
Lv 10 -> 20 = increase by 1000 blocks
Lv 20 -> 30 = increase by 1500 blocks
Lv 30 -> 50 = increase by 2000 blocks"

- knowledge enchantment not working, not receiving 2x pickaxe exp.
"Knowledge: Increases pickaxe exp gain
Lv 1 - 10% chance to gain 2 exp instead of 1
Lv 2 - 20% chance to gain 2 exp instead of 1
Lv 3 - 30% chance to gain 2 exp instead of 1
Lv 4 - 40% chance to gain 2 exp instead of 1
Lv 5 - 50% chance to gain 2 exp instead of 1
Lv 6 - 60% chance to gain 2 exp instead of 1
Lv 7 - 70% chance to gain 2 exp instead of 1
Lv 8 - 80% chance to gain 2 exp instead of 1
Lv 9 - 90% chance to gain 2 exp instead of 1
Lv 10 - 100% chance to gain 2 exp instead of 1"

- Dont think I receive orbs every 10 minutes:
"NEW WAY: Every 10 minutes 100 orbs will be given to everyone online. Add a title: "&aGAINS" "&7Everyone gained &a100 orbs""

- Lucky chests happen way too often. They are not 1%.

**Comment by FadeCloudINC** [comment]
Also please change the messages to our new network style:
"&3[&bEnchanter&3] &b<message>"

Important numbers, players or locations should be in &3

examples:
"&3[&bEnchanter&3] &3<player> &bhas leveled up to level &3<#>"
"&3[&bEnchanter&3] &bYou upgraded to pickaxe to &3fortune lv 3"

etc..

**Comment by FadeCloudINC** [comment]
- Lucky chests are not 1%, they seem to be 10%.
- Lores need to be adjusted to what I said above.
- Add a message to when your pickaxe levels up + what enchant you received.
- Make it so you dont receive pickaxe levels if you keep mining with a full inventory +  make it so you dont break blocks if you have a full inventory.
- Add an item in-game to drag and drop over your pickaxe to give it exp so we can do easier testing with the levels.
- Knowledge enchantment doesnt give me 2x exp at level 10.
- Add a spacer between the enchantments and the level information: https://gyazo.com/9910a56c8708c5b6e09c9f2516697b3d
- when mines reset, lucky chests holograms stay there: https://gyazo.com/d5f060029287ee59f489545e256b25c2

**Comment by Inkzzz** [comment]
Changes complete. Leaving this open for any further updates.

**Comment by FadeCloudINC** [comment]
Final changes/issues:
- https://gyazo.com/73b04ab965caec9c3e8e888a549ff8b0 You can receive more levels them max by leveling up your pickaxe. It should not give you an enchantment that is already maxed. If all enchants are maxed then do not give anything in return.
- Fortune changes: each level of fortune you have on your pickaxe will increase the number of blocks you receive. 
No fortune = 1 block
lv 1 fortune = 2 blocks
lv 2 fortune = 3 blocks
lv 100 fortune = 101 blocks (hence it increases by 1).
- Remove flamethrower and dragonburst enchantments completely.
- When you let the haste boost (or any kind of pickaxe boost) go away than mine again, the first and second blocks won't go straight into your inventory and will drop.
- make it so when you use a gem, all blocks broken goes towards your pickaxe exp.
- add a pickaxe exp item where, when you have one you can drag it onto your pickaxe to receive experience points.
item: glowstone dust
"&e&lMagic EXP Dust &7(Drag)"
"&7The dust particles from the legendary"
"&emages. &7apply it by dragging it onto"
"&7your pickaxe."
""
"&eExperience: <exp amount>"

**Comment by FadeCloudINC** [comment]
- https://gyazo.com/73b04ab965caec9c3e8e888a549ff8b0 You can receive more levels them max by leveling up your pickaxe. It should not give you an enchantment that is already maxed. If all enchants are maxed then do not give anything in return.
- https://prnt.sc/g2qoze dont have a single level of haste booster.
- make it so when you use a gem, all blocks broken goes towards your pickaxe exp.
- Giving a 50k exp glowstone dust and then applying would spam you with new enchantments but would level you up once when you should have leveled up a couple times.
- Sometimes glowstone dust exp doesnt apply on the pickaxe. You'll have to get another one and reapply it.

**Comment by FadeCloudINC** [comment]
- https://prnt.sc/g38hxh can still go over enchant level cap by leveling up my pickaxe. I used the glowstone dust to get my pickaxe to that level.
- NEW: addon to the fortune enchantment. Make it so that amount of blocks you receive is random. Min being 1 and max being your fortune level.

**Comment by Inkzzz** [comment]
Closing as all of the above has been done and sent off.
