### ISSUE TITLE
{Global} [PlayerPoints / Voting] Milestone voting

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#70]
https://fadecloudmc.com/forums/threads/vote-rewards.59313/

Checkup on this working correctly?

**Comment by Inkzzz** [comment]
Would you assume this to be a problem @FadeCloudINC? If so, I can take a look at it, but I know there could be some non-fixable reasonings.

**Comment by FadeCloudINC** [comment]
It's working correctly. You can only receive the milestone once per server reset. Not per vote reset.
