### ISSUE TITLE
{KitPvP} [CrazyCrates] Crates typo and quick draw

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#71]
http://prntscr.com/homnvw

It's not allowing player to skip the animation. Like you did on sb3

**Comment by Inkzzz** [comment]
Assigned Aleksey regarding the Typo. 

As for the animation, do you want players to be able to skip it, @FadeCloudINC?

**Comment by FadeCloudINC** [comment]
Requires server reboot.
