### ISSUE TITLE
Skyblock | Mobs & Spawning

### ISSUE THREAD

**Issue by Inkzzz** [FadeCloudNW/issue-tracker#75]
- [ ] Allow spawners to spawn in any condition. Meaning, if you have a pig spawner, let it spawn on bedrock or any kind of block. Also, make sure that the time in Minecraft isn't affecting spawners.
- [x] Mobs don't stack sometimes, due to the island upgrades plugin.

**Comment by kalebmmm** [comment]
New stacker plugin should solve the stacking thing. As for spawn conditions, we might have to screw with craftbukkit.
