### ISSUE TITLE
{Global} PlayerVault issue

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#76]
Players can not open 1 or more of their vaults. Message: https://fadecloudmc.com/forums/attachments/2017-10-01_00-34-09-png.16674/

{Not confirmed} I think this is linked to the issue: https://github.com/drtshock/PlayerVaults/issues/279

[Post](https://fadecloudmc.com/forums/threads/mypingsuxs-kitpvp-bug-report.55002/)
[Post](https://fadecloudmc.com/forums/threads/stinkinqs-kitpvp-bug-report.55545/)

**Comment by FadeCloudINC** [comment]
The issue should be resolved after a reboot.
