### ISSUE TITLE
{Global} [SantaMew] No items given

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#82]
SantaMew failed to give items to some players: 

https://imgur.com/a/DEP8K 
https://fadecloudmc.com/forums/attachments/2017-12-21_22-05-12-png.18127/

Has not happened to myself yet.

**Comment by Inkzzz** [comment]
Take a look at the configuration of the rewards - ensure the commands are configured correctly (format etc.)

If it all looks good, let me know and I'll look into it.

**Comment by LucKYsHoTSzZz** [comment]
Now that I think about it. The explosive snowballs are disabled. Maybe that is causing the not receiving any rewards.

**Comment by Inkzzz** [comment]
I worked on a few changes for explosive snowballs. @FadeCloudINC will test it shortly. Hopefully, this issue will be resolved shortly.

**Comment by FadeCloudINC** [comment]
Issue was with the snowballs, resolved now.
