### ISSUE TITLE
{Survival} Itemframe protection

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#85]
A random person can take the items from an item frame in claimed area which he/she is not added to

This bug might not be relevant due to the possible close reset of Survival. And the change of the current protection plugin being changed into the Towny one (with a reset).

**Comment by Inkzzz** [comment]
This is up for review considering the protection plugin being changed.

**Comment by FadeCloudINC** [comment]
Protection plugin going to be replaced after server reset. No need to continue updating our current protection plugin.
