### ISSUE TITLE
{Global} [Titles] Little thing

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#86]
http://prntscr.com/hrcmxv

Not the original of that I think it should be a [snowflake symbol / character](http://www.fileformat.info/info/unicode/char/2744/index.htm). Checkup with Mew

**Comment by FadeCloudINC** [comment]
Temp fixed. Removed the code, waiting on @Inkzzz for Unicode support.
