### ISSUE TITLE
{Prison} [Backpacks] Welp this happened

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#87]
[VIDEO](https://youtu.be/mQWLVYFdNi8?t=199)

Ok, let me just add that in the region item-drop is disabled. But the backpacks just bypass it. I suggest just making it look for free inventory spaces. Or when right clicked it just deletes the content of the backpack.

Please check up with Mew for his preferred change!

**Comment by Inkzzz** [comment]
What's the exact issue?

I can prevent backpacks being emptied in specific regions.

**Comment by LucKYsHoTSzZz** [comment]
Players are just dropping loads of blocks in spawn. And are filling player's inventories.

**Comment by Inkzzz** [comment]
I'm coming up with a solution.

**Comment by Inkzzz** [comment]
Moved ticket -> https://github.com/FadeCloudNW/FadePrisonEnchants/issues/17
