### ISSUE TITLE
{Global} [Autosell] Store items

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#94]
You can't sell a kititem with /sell hand or /sell all BUT you can with autosell...

I don't know what else is being stopped from being sold with /sell <hand\all>. Maybe go to Mew to blacklist certain items in the autosell?

_No post linked_

**Comment by kalebmmm** [comment]
AutoSell looks to the shop plugin to see what can be sold. I'm working on a refactor of AutoSell, so I'll look into this.

**Comment by kalebmmm** [comment]
Should be fixed in the latest autosell version
