### ISSUE TITLE
{Prison} [/rankup max] Disconnect due to spam

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#95]
People get kicked if they use /rankup max (Kicked for spam). This only happens when the player can rank up a decent amount in the rank ladder

Also while looking into that. Maybe create a feature where a player rank rankup when they hit the needed amount of money. Ofcourse a toggle command. /rankup toggle or so

**Comment by FadeCloudINC** [comment]
I haven’t uploaded the latest prison rank up plugin. Please send it to me and this issue will be resolved @inkzzz

**Comment by Inkzzz** [comment]
Sent to you @FadeCloudINC.
