### ISSUE TITLE
{Global} [Enchantment Table] Any version it seems

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [FadeCloudNW/issue-tracker#98]
people seem to having issues with enchanting on Fade. Most common server this occurs is Skyblock.

The enchantment table gives you the enchantments. You can click on them but they don't apply to the sword. The sword just doesn't get the enchantments and the player loses his/her xp levels.

Doesn't happen to all players it seems. But hits small amounts.

[VIDEO](https://youtu.be/ijrsRlygJpk) (Might want to turn down the sound)

**Comment by FadeCloudINC** [comment]
After tonights reboot it will be resolved.
